[features]
seeds = false
skip-lint = false

[programs.localnet]
marketplace_manager = "4GfNEbxCR7H49CpyJmrBsbZauvFhyviJXbKRZGKpNqVp"
product_manager = "5SEgBUmoD6eMxbiD2hwNwFKXPj2cU6YtddZnC3DwiCDs"
tender = "GGN4agBuV678P2M8SVJeEjeLU4maf7Rb7NH1ASMpV136"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/marketplace-manager/index.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" # token-metadata

[[test.validator.clone]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY" # bubblegum

[[test.validator.clone]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV" # noop

[[test.validator.clone]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK" # account compression
